version: '3.8'

services:
  # PostgreSQL with TimescaleDB
  postgres:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB: ingestor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d ingestor']
      interval: 10s
      timeout: 5s
      retries: 5

  # Ingestor service
  ingestor:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://user:pass@postgres:5432/ingestor
      HTTP_TIMEOUT_MS: 20000
      HTTP_RETRIES: 3
      BREAKER_FAILURE_THRESHOLD: 5
      PRIMARY_PROVIDER: bcra
      FALLBACK_PROVIDER: datos
      LOG_LEVEL: info
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Mount CA bundle if needed
      - ./infrastructure/certs:/app/certs:ro
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
